"use client";
import BookSolar from "@/components/BookSolar";
import Footer from "@/components/Footer";
import HeroSection from "@/components/HeroSection";
import Navbar from "@/components/Navbar";
import PackageCard from "@/components/products/PackageCard";
import { SolarProducts } from "@/constants/home";
import React from "react";

const Solar = () => {
  return (
    <div className="overflow-hidden">
      <Navbar />
      <HeroSection
        img="/backgroundImg/solarbg.png"
        Children={null}
        SmallImg={true}
      />

      <BookSolar />

      <div className="bg-primary py-12 md:py-20 relative overflow-hidden">
        {/* Decorative elements */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-white/5 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-0 left-0 w-80 h-80 bg-tertiary/10 rounded-full blur-3xl"></div>
        <div className="absolute top-1/2 right-1/4 w-64 h-64 bg-secondary/5 rounded-full blur-3xl animate-float"></div>
        
        <div className="globalContainer relative z-10">
          <div className="text-center mb-8 md:mb-12">
            <span className="inline-block bg-white/10 text-tertiary font-semibold text-xs sm:text-sm px-4 py-2 rounded-full mb-4 animate-fadeIn">
              ENERGY STORAGE
            </span>
            <h2 className="text-2xl md:text-4xl lg:text-5xl text-white font-bold animate-slideUp">
              Solar Batteries
            </h2>
          </div>
          
          <div className="bg-white/5 backdrop-blur-sm rounded-2xl p-6 md:p-10 border border-white/10 hover:border-white/20 transition-all duration-500 animate-fadeIn">
            <p className="text-sm md:text-lg lg:text-xl text-tertiary leading-relaxed text-center">
              Solar batteries are energy storage systems designed to store excess
              electricity generated by solar panels during the day for use when
              the sun isn&apos;t shining. These batteries allow you to capture and
              store solar power, ensuring a continuous supply of energy even at
              night or on cloudy days. Essentially, a solar battery acts like a
              backup power source, enabling you to reduce reliance on the
              electrical grid and provide power during peak demand times or power
              outages.
            </p>
            
            <div className="mt-8 p-6 bg-white/5 rounded-xl border border-white/10 hover:border-tertiary/30 transition-all duration-300">
              <p className="text-sm md:text-base lg:text-lg text-tertiary/90 leading-relaxed text-center">
                When your solar panels produce more electricity than your
                home needs, the surplus energy is sent to the solar battery instead
                of being wasted. The battery stores this excess energy for later
                use. When the sun goes down or if there is an interruption in your
                solar power generation (due to cloudy weather), the battery
                automatically discharges its stored energy to power your home. Some
                systems even allow you to manage and control the battery&apos;s charge
                through an app, giving you full visibility and control over your
                energy use.
              </p>
            </div>
          </div>
          
          {/* Feature highlights */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-10">
            {[
              { icon: "⚡", title: "24/7 Power", desc: "Energy available day and night" },
              { icon: "🔋", title: "Store Excess", desc: "Save unused solar energy" },
              { icon: "📱", title: "Smart Control", desc: "Manage via mobile app" },
            ].map((feature, idx) => (
              <div 
                key={idx}
                className="group bg-white/5 backdrop-blur-sm rounded-xl p-6 border border-white/10 hover:border-white/30 hover:bg-white/10 transition-all duration-300 cursor-pointer animate-slideUp hover:scale-[1.02]"
                style={{ animationDelay: `${idx * 100}ms` }}
              >
                <div className="text-4xl mb-3 group-hover:scale-110 transition-transform duration-300">{feature.icon}</div>
                <h3 className="text-white font-semibold text-lg mb-2">{feature.title}</h3>
                <p className="text-tertiary/80 text-sm">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
      
      <div className="bg-tertiary min-h-screen relative overflow-hidden">
        {/* Decorative elements */}
        <div className="absolute top-20 left-10 w-72 h-72 bg-primary/10 rounded-full blur-3xl"></div>
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-white/30 rounded-full blur-3xl"></div>
        
        <div className="globalContainer relative z-10 py-12 md:py-16">
          <div className="text-center mb-8 md:mb-12">
            <span className="inline-block bg-primary/10 text-primary font-semibold text-xs sm:text-sm px-4 py-2 rounded-full mb-4 animate-fadeIn">
              OUR PRODUCTS
            </span>
            <h2 className="text-2xl md:text-4xl lg:text-5xl text-primary font-bold animate-slideUp">
              Solar Battery Products
            </h2>
            <p className="text-primary/70 mt-4 text-sm md:text-base max-w-2xl mx-auto animate-fadeIn">
              Premium battery solutions for reliable energy storage
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-10 px-4 md:px-8">
            {SolarProducts.map((info, idx) => (
              <div 
                key={idx}
                className="animate-slideUp"
                style={{ animationDelay: `${idx * 150}ms` }}
              >
                <PackageCard
                  img={info.img}
                  title={info.title}
                  des1={info.des1}
                  Button={info.Button}
                />
              </div>
            ))}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Solar;
